# Generated by Django 4.0.2 on 2023-02-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('item_category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_name', models.ManyToManyField(to='ecommerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Type',
            fields=[
                ('item_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_category_name', models.ManyToManyField(to='ecommerce.Item_Category')),
            ],
        ),
    ]
